### ISSUE TITLE
Draconic Evolution Fluid Cow Soul causes world corruption when tries to mate with real Fluid Cow

### ISSUE THREAD

**Issue by h0m3us3r** [DoctorFTB/FluidCows#6]
Not sure, if I should report it here, or to the Draconic Evolution tracker, but here is how to reproduce the issue:

1. Leave cow auto-breeders overnight;
2. Come back to way too many cows;
3. Kill them with any Draconic Evolution weapon;
4. Get a Fluid Cow Soul as a drop;
5. Having no idea what it is, and thinking it is a trophy of sorts, place it near your auto-breeders;
6. Get a Fluid Cow with "Error" metadata;
7. Auto-breeder tries to breed a normal Fluid Cow with Errorred Fluid Cow;
8. Get "Server Disconnected" message immediately, and the following in the crash-report:
`java.lang.NullPointerException: Ticking entity
	at ftblag.fluidcows.gson.FCConfig.canMateWith(FCConfig.java:138)
	at ftblag.fluidcows.entity.EntityFluidCow.func_70878_b(EntityFluidCow.java:132)
	at ftblag.fluidcows.entity.ai.FluidCowAIMate.getNearbyMate(FluidCowAIMate.java:75)
	at ftblag.fluidcows.entity.ai.FluidCowAIMate.func_75250_a(FluidCowAIMate.java:42)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	.  .  .
`
9. Restart the server;
10. Get the same crash report.

**Comment by DoctorFTB** [comment]
This bug from Fluid Cows mod.

**Comment by h0m3us3r** [comment]
Same thing happens if you try to breed (even manually) fluid cows spawned by any mob spawner.

**Comment by tyler489** [comment]
I would be willing to bet this is because those mods do not keep fluid cows not data.

**Comment by DoctorFTB** [comment]
Its caused by "fluid in cow is null". If all fluids cant spawn - fluid set to null.
~
Working on fix & more content.
Sorry for wait..

**Comment by DoctorFTB** [comment]
Try 1.1.14 version.

**Comment by DoctorFTB** [comment]
Closed. Author issue ignore.
